### ISSUE TITLE
No Hassle Installation Instructions for Pineapple Tetra

### ISSUE THREAD

**Issue by shadoxx** [adde88/ManaToolkit#1]
SSH into your Pineapple just as you normally would and make sure it is connected to the WAN.

Make sure `git` is installed:
`opkg update && opkg install git`

Then, clone the Git repo directly into `/pineapple/modules`:
`git clone git://github.com/adde88/ManaToolkit.git /pineapple/modules/ManaToolkit/`

**Comment by adde88** [comment]
Thanks for adding some alternative instructions.
Almost the same procedure can be done on the Nano:

Install ```git``` to your **sd-card**.
```opkg update ;  opkg install git -d sd```

Then, clone this Git repo. to your **sd-card** folder: ```/sd/modules/```
```git clone git://github.com/adde88/ManaToolkit.git /sd/modules/ManaToolkit/```

Then we sym-link that directory to **internal-storage**, like this:
```ln -s /sd/modules/ManaToolkit /pineapple/modules/ManaToolkit```
