### ISSUE TITLE
dependencies.sh is getting an old hostapd ipk

### ISSUE THREAD

**Issue by coquinone** [adde88/ManaToolkit#2]
Had some trouble installing dependencies via pineapple's web interface.
Looking at the dependencies install script, looks like its getting a hostapd ipk that doesn't exists anymore.

Checked your other repo and replaced the url with https://github.com/adde88/hostapd-mana-openwrt/blob/master/bin/ar71xx/packages/base/hostapd-mana_2.6-4_ar71xx.ipk.

This appears to have fixed the issue.

**Comment by adde88** [comment]
thanks for noticing. fixed it now! :)
