### ISSUE TITLE
Tetra 2.0.2 - Stuck installing @ 100% CPU

### ISSUE THREAD

**Issue by moorer2k** [adde88/ManaToolkit#4]
Has been running a good 45 minutes now. Probably going to stop it. Any ways for me to check up on this issue?

![image](https://user-images.githubusercontent.com/2856413/35428123-44aaca06-0222-11e8-8736-e3b760e46283.png)

![image](https://user-images.githubusercontent.com/2856413/35428127-484f8a98-0222-11e8-9fc5-6ed7cd8292e9.png)

**Comment by moorer2k** [comment]
Oh hey, itt looks like it finished.. Closing.

**Comment by adde88** [comment]
It used hours to install on your Tetra?! 😱
