### ISSUE TITLE
Stuck Installing Dependencies 

### ISSUE THREAD

**Issue by ghost** [adde88/ManaToolkit#5]
Title says it all, it's just stuck on installing dependencies. I've installed it correctly

**Comment by Darkcast** [comment]
The dependencies take a long time to download and install, I didnt manually and I left it alone for an hour and it still havent finished.

**Comment by adde88** [comment]
Yeah. As @Darkcast said, installation on the Nano can for some people take an unusually long time.
If it's not done within an hour however something is off..
