### ISSUE TITLE
Dependencies error on install

### ISSUE THREAD

**Issue by maxpowersi** [adde88/ManaToolkit#8]
Hi!
Debuguing the dependencies.sh i think the wgets are wrong, because that URL is 404 not found on github.

Fixing them, i change sslsplit, because is not a package in the new openwrt. I am using openwrt-useful-tools for sslsplit, and mana, because i can not install the packages from: /hostapd-mana-openwrt/tree/openwrt-19.07/bin/ar71xx/packages/base (i got an error from arch.) But  asleap_2.2-1_ar71xx.ipk is missing.

Good job, regards!

Regards, and good job!

**Comment by adde88** [comment]
I'll take a look at the script asap. Some bugs came with the big fw 2.6.0 update. 
Thanks for reporting :)

**Comment by maxpowersi** [comment]
Many thanks for the help. I saw that, the dependency script is trying to install sslsplit from openwrt repo, i changed it, to use your version, in the "openwrt usefull tools", this works!, but i am getting a new error, because, asleap, and mana, fro ipk saids in my pineapple nano (last version of firmware):
Unknown package 'asleap'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for asleap found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package asleap.

trying in manual mode using: opkg install --dest sd --force-overwrite asleap_2.2-1_ar71xx.ipk

Many thanks for the help!, Good Job.
